# Generated by Django 2.2.11 on 2020-03-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('books', models.TextField(verbose_name='Books')),
                ('movies', models.TextField(verbose_name='Movies')),
                ('documentaries', models.TextField(verbose_name='Documentaries')),
                ('youtube_channels', models.TextField(verbose_name='Youtube Channels')),
                ('websites', models.TextField(verbose_name='Websites')),
                ('facebook_pages', models.TextField(verbose_name='Facebook Pages')),
                ('instagram_pages', models.TextField(verbose_name='Instagram Pages')),
            ],
        ),
    ]
