# Generated by Django 2.2.13 on 2020-07-31 19:02

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Slug')),
                ('url', models.URLField(blank=True, default='', null=True, verbose_name='URL')),
                ('type', models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('tv', 'TV Show'), ('other', 'Other')], default='other', max_length=150, verbose_name='Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_images', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('subject', models.ManyToManyField(blank=True, related_name='content', to='subjects.Subject')),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='"General knowledge", "Self development", Economics, Entertainment, Entrepreneurship, History, Miscellaneous, Philosophy, Photography, Psychology, Science, Sociology, Strategy, Technology, Trading', related_name='content_tag', to='common.Tag')),
                ('topics', tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='"General knowledge", "Self development", Economics, Entertainment, Entrepreneurship, History, Miscellaneous, Philosophy, Photography, Psychology, Science, Sociology, Strategy, Technology, Trading', related_name='content_topic', to='common.Topic')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
