# Generated by Django 2.2.13 on 2020-07-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_id',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
