# Generated by Django 2.2.11 on 2020-04-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='documentaries',
            new_name='docs',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='facebook_pages',
            new_name='fb_pages',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='instagram_pages',
            new_name='insta_pages',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='youtube_channels',
            new_name='yt_channels',
        ),
    ]
