# Generated by Django 2.2.13 on 2020-07-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_content_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('tv', 'TV Show'), ('other', 'Other')], default='other', max_length=150, verbose_name='Type'),
        ),
    ]
