# Generated by Django 2.2.11 on 2020-05-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20200405_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='books',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='fb_pages',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='insta_pages',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='websites',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='yt_channels',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('type', models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('doc', 'Documentary'), ('website', 'Website'), ('yt_channel', 'Youtube Channel'), ('social_media', 'Social Media'), ('other', 'Other')], default='other', max_length=20, verbose_name='Content Type')),
                ('creator', models.CharField(max_length=255, verbose_name='Creator')),
                ('description', models.TextField(verbose_name='Description')),
                ('link', models.URLField(unique=True, verbose_name='Link')),
                ('subject', models.ManyToManyField(to='subjects.Subject')),
            ],
        ),
    ]
