# Generated by Django 2.2.13 on 2020-07-25 09:19

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_topic'),
        ('subjects', '0002_content_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='content',
            name='topics',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='"General knowledge", "Self development", Economics, Entertainment, Entrepreneurship, History, Miscellaneous, Philosophy, Photography, Psychology, Science, Sociology, Strategy, Technology, Trading', related_name='topic', to='common.Topic'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('tv', 'TV Show'), ('youtube_channel', 'Youtube Channel'), ('youtube_video', 'Youtube Video'), ('youtube_playlist', 'Youtube Playlist'), ('other', 'Other')], default='other', max_length=150, verbose_name='Type'),
        ),
    ]
