# Generated by Django 2.2.13 on 2020-07-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20200725_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='bookmarked_by',
        ),
        migrations.RemoveField(
            model_name='content',
            name='creator',
        ),
    ]
