# Generated by Django 2.2.13 on 2020-07-25 12:31

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20200725_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='topics',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='"General knowledge", "Self development", Economics, Entertainment, Entrepreneurship, History, Miscellaneous, Philosophy, Photography, Psychology, Science, Sociology, Strategy, Technology, Trading', related_name='content_topic', to='common.Topic'),
        ),
    ]
