# Generated by Django 2.2.13 on 2020-07-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('subjects', '0006_auto_20200616_1315'), ('subjects', '0007_auto_20200622_1437'), ('subjects', '0008_auto_20200622_1448'), ('subjects', '0009_auto_20200623_2323'), ('subjects', '0010_auto_20200623_2325'), ('subjects', '0011_list_slug'), ('subjects', '0012_auto_20200625_1641'), ('subjects', '0013_auto_20200625_1648'), ('subjects', '0014_auto_20200625_1650'), ('subjects', '0015_auto_20200625_1652'), ('subjects', '0016_auto_20200625_1700'), ('subjects', '0017_auto_20200625_1702'), ('subjects', '0018_auto_20200625_2007'), ('subjects', '0019_list_description'), ('subjects', '0020_auto_20200626_0128'), ('subjects', '0021_auto_20200626_0146'), ('subjects', '0022_delete_list')]

    dependencies = [
        ('subjects', '0005_auto_20200521_1702'),
        ('users', '0003_auto_20200616_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='link',
        ),
        migrations.AddField(
            model_name='content',
            name='content_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Content URL'),
        ),
        migrations.AlterField(
            model_name='content',
            name='subject',
            field=models.ManyToManyField(related_name='content', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='content',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='content_bookmark', to='users.BucketUser', verbose_name='Bookmarked By'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('documentary', 'Documentary'), ('website', 'Website'), ('youtube_channel', 'Youtube Channel'), ('social_media', 'Social Media'), ('other', 'Other')], default='other', max_length=20, verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
