# Generated by Django 2.2.13 on 2020-06-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200616_1315'),
        ('subjects', '0005_auto_20200521_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='link',
        ),
        migrations.AddField(
            model_name='content',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark', to='users.BucketUser', verbose_name='Bookmark'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Content URL'),
        ),
        migrations.AlterField(
            model_name='content',
            name='subject',
            field=models.ManyToManyField(related_name='content', to='subjects.Subject'),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='List Name')),
                ('content', models.ManyToManyField(blank=True, related_name='content', to='subjects.Content', verbose_name='Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BucketUser')),
            ],
        ),
    ]
