# Generated by Django 2.2.13 on 2020-06-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200616_1315'),
        ('subjects', '0006_auto_20200616_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='content',
            name='content_bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='content_bookmark', to='users.BucketUser', verbose_name='Bookmarked By'),
        ),
        migrations.AddField(
            model_name='list',
            name='list_bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='list_bookmark', to='users.BucketUser', verbose_name='Bookmarked By'),
        ),
    ]
