# Generated by Django 2.2.13 on 2020-06-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20200622_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content_bookmarked_by',
            new_name='bookmarked_by',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='list_bookmarked_by',
            new_name='bookmarked_by',
        ),
    ]
