# Generated by Django 2.2.13 on 2020-06-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_auto_20200622_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('documentary', 'Documentary'), ('website', 'Website'), ('youtube_channel', 'Youtube Channel'), ('social_media', 'Social Media'), ('other', 'Other')], default='other', max_length=20, verbose_name='Content Type'),
        ),
    ]
