# Generated by Django 2.2.13 on 2020-06-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_auto_20200623_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
