# Generated by Django 2.2.13 on 2020-06-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_auto_20200623_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, verbose_name='Slug'),
        ),
    ]
