# Generated by Django 2.2.13 on 2020-06-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_auto_20200625_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
