# Generated by Django 2.2.13 on 2020-06-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0016_auto_20200625_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='list_slug',
            new_name='slug',
        ),
    ]
