# Generated by Django 2.2.13 on 2020-06-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0017_auto_20200625_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
