# Generated by Django 2.2.13 on 2020-06-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0018_auto_20200625_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
