# Generated by Django 2.2.13 on 2020-06-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0019_list_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
