# Generated by Django 2.2.13 on 2020-06-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0020_auto_20200626_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
