# Generated by Django 2.2.13 on 2020-06-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0021_auto_20200626_0146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
