# Generated by Django 2.2.13 on 2020-06-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0022_delete_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='content',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='content', to='subjects.Subject'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('documentary', 'Documentary'), ('website', 'Website'), ('youtube_channel', 'Youtube Channel'), ('social_media', 'Social Media'), ('other', 'Other')], default='other', max_length=20, verbose_name='Type'),
        ),
    ]
