# Generated by Django 2.2.13 on 2020-07-13 10:52

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    replaces = [('subjects', '0023_auto_20200626_2354'), ('subjects', '0024_auto_20200707_1905'), ('subjects', '0025_auto_20200711_2313'), ('subjects', '0026_auto_20200712_1749'), ('subjects', '0027_auto_20200713_1232')]

    dependencies = [
        ('subjects', '0022_delete_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='content',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='content', to='subjects.Subject'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('documentary', 'Documentary'), ('website', 'Website'), ('youtube_channel', 'Youtube Channel'), ('social_media', 'Social Media'), ('other', 'Other')], default='other', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('documentary', 'Documentary'), ('website', 'Website'), ('youtube_channel', 'Youtube Channel'), ('social_media', 'Social Media'), ('other', 'Other')], default='other', max_length=150, verbose_name='Type'),
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='technology, entrepreneurship, self-development, self-growth', related_name='content_tag', to='common.Tags'),
        ),
    ]
