# Generated by Django 2.2.13 on 2020-07-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0024_auto_20200707_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['title']},
        ),
    ]
