# Generated by Django 2.2.13 on 2020-07-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        ('subjects', '0002_content_tags'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
