# Generated by Django 2.2.13 on 2020-08-03 08:48

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('subjects', '0002_content_content_id'),
        ('users', '0002_auto_20200801_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('goal', models.CharField(max_length=255, verbose_name='Goal')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='path_images', verbose_name='Image')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=150, verbose_name='Visibility')),
            ],
            options={
                'ordering': ['goal'],
            },
        ),
        migrations.CreateModel(
            name='PathContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Content')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paths.Path')),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='path_content', through='paths.PathContent', to='subjects.Content'),
        ),
        migrations.AddField(
            model_name='path',
            name='topics',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='"General knowledge", "Self development", Economics, Entertainment, Entrepreneurship, History, Miscellaneous, Philosophy, Photography, Psychology, Science, Sociology, Strategy, Technology, Trading', related_name='path_topic', to='common.Topic'),
        ),
        migrations.AddField(
            model_name='path',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BucketUser'),
        ),
    ]
