# Generated by Django 2.2.13 on 2020-07-25 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BucketUser')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('plan_to_watch', 'Plan to watch'), ('on_hold', 'On-hold'), ('dropped', 'Dropped'), ('not_interested', 'Not interested')], default='completed', max_length=150, verbose_name='Status')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=150, verbose_name='Visibility')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BucketUser')),
            ],
        ),
        migrations.AddField(
            model_name='bucketuser',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarked_by', through='users.Bookmark', to='subjects.Content'),
        ),
        migrations.AddField(
            model_name='bucketuser',
            name='recommendations',
            field=models.ManyToManyField(related_name='recommended_by', through='users.Recommendation', to='subjects.Content'),
        ),
    ]
