# Generated by Django 2.2.13 on 2020-06-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20200521_1702'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketuser',
            name='blog_url',
        ),
        migrations.RemoveField(
            model_name='bucketuser',
            name='homepage_url',
        ),
        migrations.AddField(
            model_name='bucketuser',
            name='bio',
            field=models.URLField(blank=True, max_length=255, verbose_name='Bio'),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='List Name')),
                ('content', models.ManyToManyField(to='subjects.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BucketUser')),
            ],
        ),
    ]
