# Generated by Django 2.2.13 on 2020-07-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_content_content_id'),
        ('users', '0002_auto_20200725_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='bucketuser',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='bucketuser',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='bucketuser',
            name='content_bookmark',
            field=models.ManyToManyField(related_name='content_bookmarked_by', through='users.Bookmark', to='subjects.Content'),
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
