# Generated by Django 2.2.13 on 2020-08-15 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200801_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to='users.BucketUser')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.BucketUser')),
            ],
        ),
        migrations.AddField(
            model_name='bucketuser',
            name='users_following',
            field=models.ManyToManyField(through='users.FollowUser', to='users.BucketUser'),
        ),
    ]
