# Generated by Django 2.2.13 on 2020-08-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200815_1312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followuser',
            unique_together={('followed_user', 'follower')},
        ),
    ]
