# Generated by Django 2.2.13 on 2020-07-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200729_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketuser',
            name='bio',
            field=models.TextField(blank=True, max_length=100, verbose_name='Bio'),
        ),
    ]
