# Generated by Django 2.2.13 on 2020-08-15 10:20

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200815_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path, verbose_name='Profile picture'),
        ),
    ]
