# Generated by Django 2.2.13 on 2020-07-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=150, verbose_name='Visibility')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
