# Generated by Django 2.2.13 on 2020-07-13 18:26

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('common', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('bookmarked_by', models.ManyToManyField(blank=True, related_name='list_bookmark', to='users.BucketUser', verbose_name='Bookmarked By')),
                ('content', models.ManyToManyField(blank=True, related_name='content', to='subjects.Content', verbose_name='Content')),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='technology, entrepreneurship, self-development, self-growth', related_name='list_tag', to='common.Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BucketUser')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
