# Generated by Django 2.2.13 on 2020-06-26 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20200616_1315'),
        ('subjects', '0022_delete_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('bookmarked_by', models.ManyToManyField(blank=True, related_name='list_bookmark', to='users.BucketUser', verbose_name='Bookmarked By')),
                ('content', models.ManyToManyField(blank=True, related_name='content', to='subjects.Content', verbose_name='Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BucketUser')),
            ],
        ),
    ]
