# Generated by Django 2.2.13 on 2020-07-25 12:31

from django.db import migrations, models
import django.utils.timezone
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_bookmark'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='bookmarked_by',
        ),
        migrations.AddField(
            model_name='list',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='topics',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='"General knowledge", "Self development", Economics, Entertainment, Entrepreneurship, History, Miscellaneous, Philosophy, Photography, Psychology, Science, Sociology, Strategy, Technology, Trading', related_name='list_topic', to='common.Topic'),
        ),
        migrations.AddField(
            model_name='list',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=150, verbose_name='Visibility'),
        ),
    ]
