# Generated by Django 2.2.13 on 2020-07-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['name']},
        ),
    ]
