# Generated by Django 2.2.13 on 2020-07-31 19:02

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200801_0032'),
        ('common', '0001_initial'),
        ('subjects', '0001_initial'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='content', to='subjects.Content', verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='list',
            name='topics',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='"General knowledge", "Self development", Economics, Entertainment, Entrepreneurship, History, Miscellaneous, Philosophy, Photography, Psychology, Science, Sociology, Strategy, Technology, Trading', related_name='list_topic', to='common.Topic'),
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BucketUser'),
        ),
    ]
