# Generated by Django 2.2.13 on 2020-07-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200801_0032'),
        ('lists', '0002_auto_20200801_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='list_bookmarked_by',
            field=models.ManyToManyField(related_name='list_bookmark', to='users.BucketUser'),
        ),
    ]
