# Generated by Django 2.2.13 on 2020-07-13 10:05

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('lists', '0002_auto_20200711_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='technology, entrepreneurship, self-development, self-growth', related_name='list_tag', to='common.Tags'),
        ),
    ]
