# Generated by Django 2.2.13 on 2020-07-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_list_list_bookmarked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='tags',
        ),
    ]
