# Generated by Django 2.2.13 on 2020-07-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_remove_list_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='list_images', verbose_name='Image'),
        ),
    ]
